Configure columns from gridcolumnconfig json
indice-co/Indice.Platform pull request #420
Opened 2024-07-16 14:15 UTC by CostaArg

You can now configure case columns through editing the case type gridcolumnconfig

2024-07-17 08:57 UTC, pthanos requested changes

2024-07-17 08:57 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-type-specific-cases/case-type-specific-cases.component.ts
> +  setupColumns() {
είναι private. 

εφόσον εδώ λες οτι κανεις setupColumns, 1. κάντο σε ένα map, δεν χρειάζεται δυο, 2. μην κάνεις άλλη μία η οποία δεν ειναι και μαρκαρισμένη private, και κάνει λίγη ακόμη απο την δουλεια. όλη η δουλειά σε ένα σημείο, γιατί πρέπει να διαβάζω κώδικα με ψυχουλάκια για να ακολουθώ τις μεθόδους...;

2024-07-17 08:57 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/general-cases/general-cases.component.html
> +                       [title]="('cases.' + column.key[0].toLowerCase() + column.key.slice(1)) | translate">
γιατί θέλουμε ενα hashmap/dictionary μεταξύ tableColumns kai columns. Δεν μπορεί να γίνει μια τελική λίστα και να πάει foreach εδώ;

2024-07-17 08:57 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/general-cases/general-cases.component.ts
> +  setupColumns() {
κανε την protected. Δεν χρειάζεται η μία να καλεί άλλη. απλά θα κάνει override.

Επίσης πες την initColumns()

2024-07-17 11:46 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-type-specific-cases/case-type-specific-cases.component.ts
> +        this.columns = [...this.columns, ...gridConfigColumns!];
δεν πρέπει να ειναι έτσι. Αν κάνεις override τις κολώνες, θα παίρνεις μονο τις φρεσκιες, όχι οτι είχε πριν ΣΥΝ νέες. Θέλεις να διαλέξεις δικά σου; θα μου τα δώσεις ολα απο την αρχή

2024-07-17 11:48 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-type-specific-cases/case-type-specific-cases.component.ts
> +        super.initColumns();
αν δεν πετύχει η άνω κλήση, δεν θα γίνει ποτέ αυτό και δεν θα δείξεις καμία κολώνα. λέω να το κάνεις στην αρχή πριν την κλήση, ή αν δεν θέλεις να θέσει πραγματα και να κανει αεροκολωτούμπες το UI, να κάνεις exception handling στο observable σου ωστε αν δεν έρθει τουλάχιστον να κάνει την default συμπεριφορά.

2024-07-17 11:48 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/general-cases/general-cases.component.html
> +        <ng-template let-item>{{ getItemValue(item, column) }}</ng-template>
αυτό δεν ειπες οτι χτυπιέται συνέχεια και αλλάζει τα φώτα στο browser;

2024-07-17 12:02 UTC, pthanos requested changes

2024-07-17 12:02 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/general-cases/general-cases.component.ts
> +  private getValueFromProperty(obj: any, propPath: any) {
πες την getValueFromPropertyPath

2024-07-17 12:04 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/general-cases/general-cases.component.ts
> +    return item[formattedProperty];
δεν καταλαβαινω τι γινεται εδώ, βάλε περισσότερα σχόλια. Καταλαβαίνω πως πρέπει ολη η φαση του getItemValue πρέπει να γινει pipe για να μπορέσει να την παλέψει η angular να καταλαβει οτι δεν αλλαζει σε οποιοδηποτε change

2024-07-17 12:14 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/general-cases/general-cases.component.html
> +      <lib-list-column [title]="('cases.' + column.key[0].toLowerCase() + column.key.slice(1)) | translate">
δεν μπορείς να ξέρεις τι μετάφραση θα χρειαστεί ο καθένας. Πρέπει η μετάφραση να έρθει έτοιμη απο το server

2024-07-17 13:29 UTC, CostaArg commented on src/Indice.Features.Cases.App/src/app/features/cases/general-cases/general-cases.component.ts
> +    return item[formattedProperty];
Βγηκε η findAccordingValue και μπηκε η λογικη της στην getItemValue, ελπιζω τωρα να ειναι λιγο πιο κατανοητο

2024-07-23 08:04 UTC, CostaArg commented on src/Indice.Features.Cases.App/src/app/features/cases/general-cases/general-cases.component.html
> +      <lib-list-column [title]="('cases.' + column.key[0].toLowerCase() + column.key.slice(1)) | translate">
μπαινει σε todo για πιο μετα

2024-07-23 11:35 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-type-specific-cases/case-type-specific-cases.component.ts
>      this._route.params.subscribe(() => {
δεν χρειάζεται το datePipe να ερθει εδώ

2024-07-23 11:42 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/shared/pipes.services.ts
> +      formattedValue = this.datePipe.transform(value, 'dd/MM/yy, HH:mm') || '-';
γιατι πας με datepipe και δεν κανεις απλα ενα format του date object;

2024-07-26 15:24 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-type-specific-cases/case-type-specific-cases.component.ts
> +      this.initColumns();
δεν θα είχε νοημα η initColumns να ειναι μέσα στην initialize(); γιατί πρέπει να ξέρω οτι πρέπει να καλέσω;

2024-07-29 08:54 UTC, pthanos approved these changes

2024-08-22 09:06 UTC, pthanos commented
Τί κάνουμε με αυτό; τι εκκρεμότητες έχει;

2024-08-29 14:08 UTC, CostaArg commented
> Τί κάνουμε με αυτό; τι εκκρεμότητες έχει;

Τα translations ειχαν μπει στο el.json, αποφασισαμε για την ωρα να τα κουνησουμε στα τοπικα projects. Οποτε τωρα ειμαστε ετοιμοι για merge.

2024-08-30 08:44 UTC, dkarkanas approved these changes

2024-08-30 08:44 UTC, merged