Show correlated cases in case details
indice-co/Indice.Platform pull request #428
Opened 2024-08-29 13:12 UTC by CostaArg

Can now show a table with the cases that are correlated with the opened case

2024-08-30 08:11 UTC, pthanos commented
1ο: πρέπει όπου λέμε -co-related να το πούμε απλά related, corellation είναι άλλο πράγμα, χωρίς co είναι αρκετό. 
2ο: πρέπει να κάνουμε νέο /getRelatedCases ή να ορίσουμε απλά ένα φίλτρο που θα πάει στην GetCases και θα φέρει ότι πρέπει; Νομίζω πρέπει να μπει και απο την Get, για να μπορεί να την καλέσει και κάποιος που ΔΕΝ ειναι το UI. Μήπως ήδη μπορεί να γίνει με το σωστό query;

2024-08-30 08:12 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs
> +        var list = _dbContext.Cases.AsNoTracking()
δεν έχεις πιάσει περίπτωση που δεν εχει ID

2024-08-30 08:15 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Interfaces/IAdminCaseService.cs
> +    Task<IEnumerable<Guid>> GetCorrelatedCaseIds(ClaimsPrincipal user, Guid caseId);
GetRelatedCases

2024-08-30 08:15 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Controllers/AdminCasesController.cs
> +    public async Task<IActionResult> GetCorrelatedCases([FromRoute] Guid caseId) {
related

2024-08-30 08:20 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.html
> +                          <ng-container *ngIf="correlatedCasesIds$ | async as correlatedCasesIds">
πολύ ωραία η υλοποίηση, μπράβο.

2024-08-30 08:24 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-correlated/case-correlated.component.html
> +      entry
εδώ δεν έχεις τελειώσει;

2024-11-15 14:59 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-correlated/case-correlated.component.ts
> +  @Input() correlatedCasesIds: string[] | undefined;
related

2024-11-15 15:07 UTC, pthanos requested changes

2024-11-15 15:07 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-correlated/case-correlated.component.ts
> +export class CaseCorrelatedComponent implements OnInit {
RelatedCasesComponent

2024-11-15 15:07 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs
> +        var relationKey = @case.Metadata["ExternalRelationKey"];
se const

2024-11-15 15:07 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs
> +        var list = _dbContext.Cases.AsNoTracking()
Για να φιλτράρεις cases που δεν ανήκουν σε αυτόν που κοιτά, πρέπει να προσθέσεις και αυτή τη γραμμή.

query = await _memberAuthorizationProvider.GetCaseMembership(query, user);

για να προσθέσει τα where που χρειάζεται απο το membership και να κόψει αυτα που δεν πρέπει να δεις.

2024-11-19 15:55 UTC, CostaArg commented on src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs
> +        var list = _dbContext.Cases.AsNoTracking()
Το εκανα refactor και χρησιμοποιω τη καινουρια μεθοδο "GetCases" η οποια λειτουργει με το "AccessLevel"

2024-11-19 15:56 UTC, CostaArg commented
![image](https://github.com/user-attachments/assets/e9a4c2e4-8c55-4cdb-b8b2-93f91ccb230a)
![image](https://github.com/user-attachments/assets/c922df88-7eb5-4bf8-8e8d-931c0b1291d0)
@pthanos for your input

2024-11-20 10:16 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/case-detail-page.component.html
> +                        <div class="bg-white shadow rounded-sm">
πάρε όλη την html και βάλε την στον component, μαζί με τα if klp. Ας το κάνει ο μέσα ολο αυτό, δεν χρειάζεται να ειναι μισό στον πατέρα και μισο στο παιδί

2024-11-20 10:18 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/related-cases/related-cases.component.html
> +        [ngClass]="{'bg-blue-100': relatedCase.id === currentCaseId, 'hover:bg-gray-100': true}">
έτσι θα φαίνεται και λινκ προς τον εαυτό του. Να μην φαίνεται καθόλου ο εαυτός. Αλλά αυτό μηπως πρέπει να το λύνει ο σερβερ και να μην βάζει μέσα στην λιστα το current;

2024-11-20 10:19 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Interfaces/IAdminCaseService.cs
> +    /// <summary>Gets the related cases for a case.</summary>
κάπου πρέπει να πεις ότι ολη η μαγεία βασίζεται στο metadata.ExternalRelationKey. Αυτό υπάρχει μια κλάση να το κάνουμε λιγο document;

2024-11-20 10:25 UTC, CostaArg commented on src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/related-cases/related-cases.component.html
> +        [ngClass]="{'bg-blue-100': relatedCase.id === currentCaseId, 'hover:bg-gray-100': true}">
Ετσι το πηγα στην αρχη, το εκανα filter out τελειως, αλλα μετα ειχαμε πει οτι αν ειναι ας φαινεται στο πινακακι και να κανουμε highlight το case στο οποιο βρισκομαστε. Και ετσι εχω κανει αν δεις απο το screenshot, βαζω με "μπλε" εκει που ειμαι. Να το κρατησω ετσι οπως ειμαι?

2024-11-20 10:36 UTC, CostaArg commented on src/Indice.Features.Cases.AspNetCore/Interfaces/IAdminCaseService.cs
> +    /// <summary>Gets the related cases for a case.</summary>
Εβαλα τις αλλαγες στο changelog

2024-11-20 10:44 UTC, pthanos commented on src/Indice.Features.Cases.App/src/app/features/cases/case-detail-page/related-cases/related-cases.component.html
> +        [ngClass]="{'bg-blue-100': relatedCase.id === currentCaseId, 'hover:bg-gray-100': true}">
ναι εχεις δικιο. αλλα να μην ειναι link.

2024-11-20 10:45 UTC, pthanos commented on src/Indice.Features.Cases.AspNetCore/Controllers/AdminCasesController.cs
> +    /// <summary>Gets the ids of the related cases for a case.</summary>
βαλε εδώ το property που πρέπει να θεσει το case για να γινει related, δηλαδή κανε document το μεσα σου εδώ που εισαι απέξω και δινεις interface

2024-11-21 07:05 UTC, pthanos approved these changes

2024-11-21 07:05 UTC, merged