draft - allow action to modify case data
indice-co/Indice.Platform pull request #459
Opened 2024-11-18 09:05 UTC by NikosDevPhp

2024-11-18 10:10 UTC, cleftheris commented
Don't try to mutate by path and value. Instead try to merge using the JsonPatch spec https://github.com/json-everything/json-everything/blob/master/src/JsonPatch.Tests/PatchExtensionTests.cs

This essentially allows one to give the partial object and merge with the initial.

2024-11-22 11:26 UTC, pthanos requested changes

2024-11-22 11:31 UTC, NikosDevPhp commented on test/Indice.Features.Cases.AspNetCore.Tests/CaseDataExtensions.cs
> +        return JsonNode.Parse(((JsonElement)converted).GetRawText())!;
Αυτο προσπαθεί να τα περάσει από converter που έχουμε στο ef core για να εξομοιωσει το πως παιρνουμε από την βάση τα data

2024-11-22 12:01 UTC, NikosDevPhp commented on src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs
> +        // todo: ask Dimitris if we can use that
@dkarkanas Γενικά δεν εχω καταλαβει πληρως την συμπεριφορά.
Όταν έρχεται από http είναι συνηθως JObject newtonsoft γιατι μπαινει η Elsa.
Όταν καλείται από το cases dll, όταν το παίρνουμε από βάση ειναι JsonElement.
Έχω δει περίεργη συμπεριφορά οταν καλω δυο φορες την patchData που κανει fetch την πρωτη φορα ειναι JsonElement και την δευτερη ειναι JObject.

Νομιζω σωστος ειναι ο τρόπος που το παιρνω στο AdminCaseService θα δω λιγο περιπτωσεις.

2024-11-22 12:01 UTC, NikosDevPhp commented on src/Indice.Features.Cases.AspNetCore/Services/AdminCaseService.cs
> +        var caseData = (await GetCaseById(user, caseId, false)).DataAs<JsonObject>();
Μιλησαμε λίγο με Κωνσταντίνο, είναι άλλο PR αυτό, θελει δυνατό regression.

2024-11-22 13:35 UTC, pthanos commented on test/Indice.Features.Cases.AspNetCore.Tests/JsonDocumentTests.cs
> +        caseData.Merge(new { foo = new List<object> { new { qux = (string)null! } } }.ToJsonNode());
αυτο μου φαίνεται κουφό, αν έχω ενα foo = [1,2,3] πως θα πω 2=null για να το σβήσω; δεν το πιάνω. αλλα οκ λεπτομερεια.

2024-11-25 14:11 UTC, NikosDevPhp commented on src/Indice.Features.Cases.AspNetCore/Models/PatchJsonPathRequest.cs
> +    public OperationType Op { get; set; }
Ειναι σύμφωνα με το rfc https://datatracker.ietf.org/doc/html/rfc6902#section-4.1 και ειναι λιγοτερο verbose για τον client.

2024-11-25 17:34 UTC, dkarkanas commented on src/Indice.Features.Cases.AspNetCore/Controllers/AdminCaseDataController.cs
> +[Route($"{ApiPrefixes.CasesApiTemplatePrefixPlaceholder}/manage/case-data")]
καλο ειναι, δεν ξερω αν εχει νοημα να παει σε δικο του controller (αλλα και το attachment ξεχωριστο το εχουμε βλεπω..) οποτε δεν λεω και κατι ουσιαστικό, απλά γραφω σχόλια για να πάει ειδοποίηση σε όλους μάλλον.

2024-11-26 08:53 UTC, merged